x-dotnet-tmpfs: &dotnet-tmpfs
  - /src/src/Core/Heartbeat.Core/bin:exec
  - /src/src/Core/Heartbeat.Core/obj:exec
  - /src/src/Backend/Heartbeat.Api/bin:exec
  - /src/src/Backend/Heartbeat.Api/obj:exec
  - /src/src/Backend/Heartbeat.Application/bin:exec
  - /src/src/Backend/Heartbeat.Application/obj:exec
  - /src/src/Backend/Heartbeat.Infrastructure/bin:exec
  - /src/src/Backend/Heartbeat.Infrastructure/obj:exec

services:
  api:
    build:
      target: development
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
    volumes:
      - type: bind
        source: .
        target: /src
    tmpfs: *dotnet-tmpfs

  docs:
    build:
      target: development
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - type: bind
        source: .
        target: /src
      - type: volume
        source: docs-node-modules
        target: /src/src/Docs/Heartbeat.Docs/node_modules
      - type: volume
        source: docs-next
        target: /src/src/Docs/Heartbeat.Docs/.next

volumes:
  docs-node-modules:
  docs-next:
