<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Hub/Heartbeat.Hub.Runtime/Heartbeat.Hub.Runtime.csproj" />
    <ProjectReference Include="../../Hub/Heartbeat.Hub/Heartbeat.Hub.csproj" />
    <ProjectReference Include="../../Collectors/Heartbeat.Collector.Desktop/Heartbeat.Collector.Desktop.csproj" />
  </ItemGroup>
</Project>
