<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="VRChat.API" Version="2.20.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\protocol\Heartbeat.Collection.CollectorProtocol\Heartbeat.Collection.CollectorProtocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Heartbeat.Collector.VRChat.Tests" />
  </ItemGroup>

</Project>
