using Heartbeat.Core.DTOs.Input;

namespace Heartbeat.Desktop.Mac.Input;

/// <summary>
/// macOS HIToolbox virtual keycodes describe physical key positions. Map them to
/// Heartbeat's platform-neutral position contract without consulting the active layout.
/// </summary>
public static class MacKeyPositionMapper
{
    public static bool TryMap(ushort nativeKeyCode, out InputKeyPosition position)
    {
        position = nativeKeyCode switch
        {
            0x00 => InputKeyPosition.KeyA,
            0x01 => InputKeyPosition.KeyS,
            0x02 => InputKeyPosition.KeyD,
            0x03 => InputKeyPosition.KeyF,
            0x04 => InputKeyPosition.KeyH,
            0x05 => InputKeyPosition.KeyG,
            0x06 => InputKeyPosition.KeyZ,
            0x07 => InputKeyPosition.KeyX,
            0x08 => InputKeyPosition.KeyC,
            0x09 => InputKeyPosition.KeyV,
            0x0A => InputKeyPosition.IntlBackslash,
            0x0B => InputKeyPosition.KeyB,
            0x0C => InputKeyPosition.KeyQ,
            0x0D => InputKeyPosition.KeyW,
            0x0E => InputKeyPosition.KeyE,
            0x0F => InputKeyPosition.KeyR,
            0x10 => InputKeyPosition.KeyY,
            0x11 => InputKeyPosition.KeyT,
            0x12 => InputKeyPosition.Digit1,
            0x13 => InputKeyPosition.Digit2,
            0x14 => InputKeyPosition.Digit3,
            0x15 => InputKeyPosition.Digit4,
            0x16 => InputKeyPosition.Digit6,
            0x17 => InputKeyPosition.Digit5,
            0x18 => InputKeyPosition.Equal,
            0x19 => InputKeyPosition.Digit9,
            0x1A => InputKeyPosition.Digit7,
            0x1B => InputKeyPosition.Minus,
            0x1C => InputKeyPosition.Digit8,
            0x1D => InputKeyPosition.Digit0,
            0x1E => InputKeyPosition.BracketRight,
            0x1F => InputKeyPosition.KeyO,
            0x20 => InputKeyPosition.KeyU,
            0x21 => InputKeyPosition.BracketLeft,
            0x22 => InputKeyPosition.KeyI,
            0x23 => InputKeyPosition.KeyP,
            0x24 => InputKeyPosition.Enter,
            0x25 => InputKeyPosition.KeyL,
            0x26 => InputKeyPosition.KeyJ,
            0x27 => InputKeyPosition.Quote,
            0x28 => InputKeyPosition.KeyK,
            0x29 => InputKeyPosition.Semicolon,
            0x2A => InputKeyPosition.Backslash,
            0x2B => InputKeyPosition.Comma,
            0x2C => InputKeyPosition.Slash,
            0x2D => InputKeyPosition.KeyN,
            0x2E => InputKeyPosition.KeyM,
            0x2F => InputKeyPosition.Period,
            0x30 => InputKeyPosition.Tab,
            0x31 => InputKeyPosition.Space,
            0x32 => InputKeyPosition.Backquote,
            0x33 => InputKeyPosition.Backspace,
            0x35 => InputKeyPosition.Escape,
            0x36 => InputKeyPosition.MetaRight,
            0x37 => InputKeyPosition.MetaLeft,
            0x38 => InputKeyPosition.ShiftLeft,
            0x39 => InputKeyPosition.CapsLock,
            0x3A => InputKeyPosition.AltLeft,
            0x3B => InputKeyPosition.ControlLeft,
            0x3C => InputKeyPosition.ShiftRight,
            0x3D => InputKeyPosition.AltRight,
            0x3E => InputKeyPosition.ControlRight,
            0x41 => InputKeyPosition.NumpadDecimal,
            0x43 => InputKeyPosition.NumpadMultiply,
            0x45 => InputKeyPosition.NumpadAdd,
            0x47 => InputKeyPosition.NumLock,
            0x4B => InputKeyPosition.NumpadDivide,
            0x4C => InputKeyPosition.NumpadEnter,
            0x4E => InputKeyPosition.NumpadSubtract,
            0x52 => InputKeyPosition.Numpad0,
            0x53 => InputKeyPosition.Numpad1,
            0x54 => InputKeyPosition.Numpad2,
            0x55 => InputKeyPosition.Numpad3,
            0x56 => InputKeyPosition.Numpad4,
            0x57 => InputKeyPosition.Numpad5,
            0x58 => InputKeyPosition.Numpad6,
            0x59 => InputKeyPosition.Numpad7,
            0x5B => InputKeyPosition.Numpad8,
            0x5C => InputKeyPosition.Numpad9,
            0x60 => InputKeyPosition.F5,
            0x61 => InputKeyPosition.F6,
            0x62 => InputKeyPosition.F7,
            0x63 => InputKeyPosition.F3,
            0x64 => InputKeyPosition.F8,
            0x65 => InputKeyPosition.F9,
            0x67 => InputKeyPosition.F11,
            0x6D => InputKeyPosition.F10,
            0x6E => InputKeyPosition.ContextMenu,
            0x6F => InputKeyPosition.F12,
            0x73 => InputKeyPosition.Home,
            0x74 => InputKeyPosition.PageUp,
            0x75 => InputKeyPosition.Delete,
            0x76 => InputKeyPosition.F4,
            0x77 => InputKeyPosition.End,
            0x78 => InputKeyPosition.F2,
            0x79 => InputKeyPosition.PageDown,
            0x7A => InputKeyPosition.F1,
            0x7B => InputKeyPosition.ArrowLeft,
            0x7C => InputKeyPosition.ArrowRight,
            0x7D => InputKeyPosition.ArrowDown,
            0x7E => InputKeyPosition.ArrowUp,
            _ => default,
        };
        return position != default;
    }
}
