<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <ProjectReference Include="../Heartbeat.Hub.Client/Heartbeat.Hub.Client.csproj" />
  </ItemGroup>
</Project>
