<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Heartbeat.Collector.Reference.ManagedProcess</AssemblyName>
    <RootNamespace>Heartbeat.Collector.Reference.ManagedProcess</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Heartbeat.Collector.Reference.ManagedProcess.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\protocol\Heartbeat.Collection.CollectorProtocol\Heartbeat.Collection.CollectorProtocol.csproj" />
  </ItemGroup>

</Project>
