#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Project helpers deliberately live below the shared wizard library. Compose
# interpolates unquoted and double-quoted dotenv values, so local values are
# stored single-quoted and apostrophes are escaped according to Compose syntax.

PROJECT_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
cd "$PROJECT_ROOT"
FINAL_ENV_FILE="$PROJECT_ROOT/.env.local"
STAGING_ENV_FILE=""
ACTIVE_TEMP_FILE=""
ORIGINAL_OWNER_ID=""
AUTH_DASHBOARD_URL="https://auth.shenxianovo.com/dashboard/api-keys"
DEFAULT_AUTH_AUTHORITY="https://auth.shenxianovo.com"

fail() {
  printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

require_interactive_terminal() {
  [[ -t 0 ]] || fail "Setup needs an interactive terminal. Run ./scripts/setup.sh directly."
}

cleanup_staging() {
  if [[ -n "$ACTIVE_TEMP_FILE" && -f "$ACTIVE_TEMP_FILE" && ! -L "$ACTIVE_TEMP_FILE" ]]; then
    rm -f -- "$ACTIVE_TEMP_FILE"
  fi
  if [[ -n "$STAGING_ENV_FILE" && -f "$STAGING_ENV_FILE" && ! -L "$STAGING_ENV_FILE" ]]; then
    rm -f -- "$STAGING_ENV_FILE"
  fi
}

prepare_staging() {
  local line
  umask 077
  [[ ! -L "$FINAL_ENV_FILE" ]] || fail "$FINAL_ENV_FILE must not be a symbolic link."
  if [[ -e "$FINAL_ENV_FILE" && ! -f "$FINAL_ENV_FILE" ]]; then
    fail "$FINAL_ENV_FILE exists but is not a regular file."
  fi
  if [[ -f "$FINAL_ENV_FILE" ]]; then
    chmod 600 "$FINAL_ENV_FILE"
    ORIGINAL_OWNER_ID=$(config_existing_from "$FINAL_ENV_FILE" HEARTBEAT_OWNER_ID || true)
  fi

  trap cleanup_staging EXIT
  trap 'exit 130' HUP INT TERM
  STAGING_ENV_FILE=$(mktemp "$PROJECT_ROOT/.env.local.setup.XXXXXX")
  chmod 600 "$STAGING_ENV_FILE"
  if [[ -f "$FINAL_ENV_FILE" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      printf '%s\n' "$line" >> "$STAGING_ENV_FILE"
    done < "$FINAL_ENV_FILE"
  fi
  ENV_FILE="$STAGING_ENV_FILE"
}

ensure_config_file() {
  umask 077
  [[ ! -L "$ENV_FILE" ]] || fail "$ENV_FILE must not be a symbolic link."
  if [[ -e "$ENV_FILE" && ! -f "$ENV_FILE" ]]; then
    fail "$ENV_FILE exists but is not a regular file."
  fi
  if [[ ! -e "$ENV_FILE" ]]; then
    : > "$ENV_FILE"
  fi
  chmod 600 "$ENV_FILE"
}

trim_space() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

decode_single_quoted() {
  local value="$1" result="" index char next
  value="${value:1:${#value}-2}"
  for ((index = 0; index < ${#value}; index++)); do
    char="${value:index:1}"
    if [[ "$char" == "\\" && $((index + 1)) -lt ${#value} ]]; then
      next="${value:index+1:1}"
      if [[ "$next" == "'" ]]; then
        result+="'"
        index=$((index + 1))
        continue
      fi
    fi
    result+="$char"
  done
  printf '%s' "$result"
}

decode_double_quoted() {
  local value="$1" result="" index char next
  value="${value:1:${#value}-2}"
  for ((index = 0; index < ${#value}; index++)); do
    char="${value:index:1}"
    if [[ "$char" == "\\" && $((index + 1)) -lt ${#value} ]]; then
      index=$((index + 1))
      next="${value:index:1}"
      case "$next" in
        n) result+=$'\n' ;;
        r) result+=$'\r' ;;
        t) result+=$'\t' ;;
        '"'|'\\') result+="$next" ;;
        *) result+="\\$next" ;;
      esac
    else
      result+="$char"
    fi
  done
  printf '%s' "$result"
}

config_existing_from() {
  local file="$1" key="$2" line="" raw
  [[ -f "$file" ]] || return 1
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" == "$key="* ]] || continue
    raw="${line#*=}"
  done < "$file"
  [[ -n "${raw+x}" ]] || return 1
  raw=$(trim_space "$raw")
  if [[ ${#raw} -ge 2 && "${raw:0:1}" == "'" && "${raw: -1}" == "'" ]]; then
    decode_single_quoted "$raw"
  elif [[ ${#raw} -ge 2 && "${raw:0:1}" == '"' && "${raw: -1}" == '"' ]]; then
    decode_double_quoted "$raw"
  else
    raw="${raw%%[[:space:]]#*}"
    trim_space "$raw"
  fi
}

config_existing() {
  config_existing_from "$ENV_FILE" "$1"
}

dotenv_quote() {
  local value="$1" index char
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || fail "Configuration values must fit on one line."
  printf "'"
  for ((index = 0; index < ${#value}; index++)); do
    char="${value:index:1}"
    if [[ "$char" == "'" ]]; then
      printf '%s' "\\'"
    else
      printf '%s' "$char"
    fi
  done
  printf "'"
}

config_write() {
  local key="$1" value="$2" tmp line encoded
  ensure_config_file
  encoded=$(dotenv_quote "$value")
  ACTIVE_TEMP_FILE=$(mktemp "$PROJECT_ROOT/.env.local.tmp.XXXXXX")
  tmp="$ACTIVE_TEMP_FILE"
  chmod 600 "$tmp"
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" == "$key="* ]] && continue
    printf '%s\n' "$line" >> "$tmp"
  done < "$ENV_FILE"
  printf '%s=%s\n' "$key" "$encoded" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  ACTIVE_TEMP_FILE=""
  chmod 600 "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ saved%s %s → .env.local\n' "$GREEN" "$RESET" "$key"
}

commit_config() {
  chmod 600 "$STAGING_ENV_FILE"
  mv "$STAGING_ENV_FILE" "$FINAL_ENV_FILE"
  STAGING_ENV_FILE=""
  ENV_FILE="$FINAL_ENV_FILE"
  chmod 600 "$FINAL_ENV_FILE"
}

ask_required_secret() {
  local key="$1" prompt="$2" current input
  current=$(config_existing "$key" || true)
  while true; do
    if [[ -n "$current" ]]; then
      printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    IFS= read -rs input
    printf '\n'
    [[ -z "$input" && -n "$current" ]] && input="$current"
    if [[ -n "$input" ]]; then
      printf -v "$key" '%s' "$input"
      return
    fi
    warn "A value is required."
  done
}

ask_with_default() {
  local key="$1" prompt="$2" fallback="$3" current input normalized
  current=$(config_existing "$key" || true)
  while true; do
    if [[ -n "$current" ]]; then
      printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
      printf '  %s%s%s %s[%s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$fallback" "$RESET"
    fi
    IFS= read -r input
    if [[ -z "$input" ]]; then
      input="${current:-$fallback}"
    fi
    normalized=$(trim_space "$input")
    if [[ -z "$normalized" ]]; then
      warn "A value is required."
    elif [[ ${#normalized} -gt 255 ]]; then
      warn "Use at most 255 characters."
    else
      printf -v "$key" '%s' "$normalized"
      return
    fi
  done
}

generate_hub_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    od -An -N32 -tx1 /dev/urandom | tr -d '[:space:]'
  fi
}

is_uuid() {
  [[ "$1" =~ ^[[:xdigit:]]{8}-[[:xdigit:]]{4}-[[:xdigit:]]{4}-[[:xdigit:]]{4}-[[:xdigit:]]{12}$ ]]
}

compose_with_staging_env() (
  unset AUTH_AUTHORITY HEARTBEAT_API_KEY HEARTBEAT_OWNER_ID HEARTBEAT_HUB_TOKEN
  unset HEARTBEAT_COLLECTOR_TARGET HEARTBEAT_COLLECTOR_DISPLAY_NAME
  docker compose --env-file "$ENV_FILE" "$@"
)

check_owner() {
  local output owner existing_owner normalized_owner normalized_existing_owner
  command -v docker >/dev/null 2>&1 || fail "Docker is required to validate the Auth API key."
  docker compose version >/dev/null 2>&1 || fail "Docker Compose is required to validate the Auth API key."

  say "Building the Hub authentication checker..."
  compose_with_staging_env build hub || fail "Hub build failed; setup is incomplete."
  say "Checking the API key with Auth..."
  if ! output=$(compose_with_staging_env run --rm --no-deps hub --check-auth); then
    fail "Auth rejected the API key or could not be reached; saved Owner binding was not changed."
  fi
  if [[ "$output" =~ ^[[:space:]]*\{[[:space:]]*\"ownerId\"[[:space:]]*:[[:space:]]*\"([[:xdigit:]]{8}-[[:xdigit:]]{4}-[[:xdigit:]]{4}-[[:xdigit:]]{4}-[[:xdigit:]]{12})\"[[:space:]]*\}[[:space:]]*$ ]]; then
    owner="${BASH_REMATCH[1]}"
  else
    fail "Hub returned an invalid authentication result; saved Owner binding was not changed."
  fi

  existing_owner="$ORIGINAL_OWNER_ID"
  normalized_owner=$(printf '%s' "$owner" | tr '[:upper:]' '[:lower:]')
  normalized_existing_owner=$(printf '%s' "$existing_owner" | tr '[:upper:]' '[:lower:]')
  if [[ -n "$existing_owner" ]] && is_uuid "$existing_owner" \
    && [[ "$normalized_existing_owner" != "$normalized_owner" ]]; then
    fail "This API key belongs to a different Owner. Stop Hub and explicitly reset its local data and Owner binding before changing accounts. HEARTBEAT_OWNER_ID was left unchanged."
  fi
  config_write HEARTBEAT_OWNER_ID "$owner"
}

require_interactive_terminal
prepare_staging
TOTAL_STAGES=3

banner "Heartbeat local setup"

stage "Auth API key"
say "Heartbeat Hub exchanges this API key for JWTs and renews them when needed."
open_url "$AUTH_DASHBOARD_URL"
if [[ -n "$(config_existing HEARTBEAT_API_KEY || true)" ]]; then
  step "An API key is already saved. Press Enter below to keep it, or create and paste a replacement."
else
  step "In the Auth dashboard, create an API key for Heartbeat and copy it."
fi
ask_required_secret HEARTBEAT_API_KEY "Paste the API key:"

AUTH_AUTHORITY=$(config_existing AUTH_AUTHORITY || true)
AUTH_AUTHORITY="${AUTH_AUTHORITY:-$DEFAULT_AUTH_AUTHORITY}"
HEARTBEAT_HUB_TOKEN=$(config_existing HEARTBEAT_HUB_TOKEN || true)
if [[ ${#HEARTBEAT_HUB_TOKEN} -lt 32 || "$HEARTBEAT_HUB_TOKEN" == "$HEARTBEAT_API_KEY" ]]; then
  HEARTBEAT_HUB_TOKEN=$(generate_hub_token)
  note "Generated a separate local Hub token."
fi
config_write AUTH_AUTHORITY "$AUTH_AUTHORITY"
config_write HEARTBEAT_API_KEY "$HEARTBEAT_API_KEY"
config_write HEARTBEAT_HUB_TOKEN "$HEARTBEAT_HUB_TOKEN"

stage "Owner verification"
say "Hub will validate the API key without starting HTTP or opening its SQLite database."
check_owner

stage "Collector identity"
HOSTNAME_DEFAULT=$(hostname -s 2>/dev/null || hostname 2>/dev/null || printf 'local-host')
ask_with_default HEARTBEAT_COLLECTOR_TARGET "Collector Target:" "$HOSTNAME_DEFAULT"
ask_with_default HEARTBEAT_COLLECTOR_DISPLAY_NAME "Collector display name:" "$HOSTNAME_DEFAULT"
config_write HEARTBEAT_COLLECTOR_TARGET "$HEARTBEAT_COLLECTOR_TARGET"
config_write HEARTBEAT_COLLECTOR_DISPLAY_NAME "$HEARTBEAT_COLLECTOR_DISPLAY_NAME"

commit_config
finish
