using Heartbeat.Core.DTOs.Input;

namespace Heartbeat.Agent.Utils;

/// <summary>
/// 把 Windows Set-1 scan code 投影到 Heartbeat 的平台无关物理键位置。
/// 主映射不读取 VirtualKey，因此活动键盘布局与产出的字符不会改变结果；只有共享
/// scan code 0x45 的 Pause / NumLock 需要借原生 VirtualKey 消歧。
/// </summary>
public static class WindowsKeyPositionMapper
{
    public static bool TryMap(
        WindowsNativeKeyObservation observation,
        out InputKeyPosition position)
    {
        position = (observation.ScanCode, observation.IsExtended) switch
        {
            (0x01, false) => InputKeyPosition.Escape,
            (0x02, false) => InputKeyPosition.Digit1,
            (0x03, false) => InputKeyPosition.Digit2,
            (0x04, false) => InputKeyPosition.Digit3,
            (0x05, false) => InputKeyPosition.Digit4,
            (0x06, false) => InputKeyPosition.Digit5,
            (0x07, false) => InputKeyPosition.Digit6,
            (0x08, false) => InputKeyPosition.Digit7,
            (0x09, false) => InputKeyPosition.Digit8,
            (0x0A, false) => InputKeyPosition.Digit9,
            (0x0B, false) => InputKeyPosition.Digit0,
            (0x0C, false) => InputKeyPosition.Minus,
            (0x0D, false) => InputKeyPosition.Equal,
            (0x0E, false) => InputKeyPosition.Backspace,
            (0x0F, false) => InputKeyPosition.Tab,
            (0x10, false) => InputKeyPosition.KeyQ,
            (0x11, false) => InputKeyPosition.KeyW,
            (0x12, false) => InputKeyPosition.KeyE,
            (0x13, false) => InputKeyPosition.KeyR,
            (0x14, false) => InputKeyPosition.KeyT,
            (0x15, false) => InputKeyPosition.KeyY,
            (0x16, false) => InputKeyPosition.KeyU,
            (0x17, false) => InputKeyPosition.KeyI,
            (0x18, false) => InputKeyPosition.KeyO,
            (0x19, false) => InputKeyPosition.KeyP,
            (0x1A, false) => InputKeyPosition.BracketLeft,
            (0x1B, false) => InputKeyPosition.BracketRight,
            (0x1C, false) => InputKeyPosition.Enter,
            (0x1C, true) => InputKeyPosition.NumpadEnter,
            (0x1D, false) => InputKeyPosition.ControlLeft,
            (0x1D, true) => InputKeyPosition.ControlRight,
            (0x1E, false) => InputKeyPosition.KeyA,
            (0x1F, false) => InputKeyPosition.KeyS,
            (0x20, false) => InputKeyPosition.KeyD,
            (0x21, false) => InputKeyPosition.KeyF,
            (0x22, false) => InputKeyPosition.KeyG,
            (0x23, false) => InputKeyPosition.KeyH,
            (0x24, false) => InputKeyPosition.KeyJ,
            (0x25, false) => InputKeyPosition.KeyK,
            (0x26, false) => InputKeyPosition.KeyL,
            (0x27, false) => InputKeyPosition.Semicolon,
            (0x28, false) => InputKeyPosition.Quote,
            (0x29, false) => InputKeyPosition.Backquote,
            (0x2A, false) => InputKeyPosition.ShiftLeft,
            (0x2B, false) => InputKeyPosition.Backslash,
            (0x2C, false) => InputKeyPosition.KeyZ,
            (0x2D, false) => InputKeyPosition.KeyX,
            (0x2E, false) => InputKeyPosition.KeyC,
            (0x2F, false) => InputKeyPosition.KeyV,
            (0x30, false) => InputKeyPosition.KeyB,
            (0x31, false) => InputKeyPosition.KeyN,
            (0x32, false) => InputKeyPosition.KeyM,
            (0x33, false) => InputKeyPosition.Comma,
            (0x34, false) => InputKeyPosition.Period,
            (0x35, false) => InputKeyPosition.Slash,
            (0x35, true) => InputKeyPosition.NumpadDivide,
            (0x36, false) => InputKeyPosition.ShiftRight,
            (0x37, false) => InputKeyPosition.NumpadMultiply,
            (0x37, true) => InputKeyPosition.PrintScreen,
            (0x38, false) => InputKeyPosition.AltLeft,
            (0x38, true) => InputKeyPosition.AltRight,
            (0x39, false) => InputKeyPosition.Space,
            (0x3A, false) => InputKeyPosition.CapsLock,
            (0x3B, false) => InputKeyPosition.F1,
            (0x3C, false) => InputKeyPosition.F2,
            (0x3D, false) => InputKeyPosition.F3,
            (0x3E, false) => InputKeyPosition.F4,
            (0x3F, false) => InputKeyPosition.F5,
            (0x40, false) => InputKeyPosition.F6,
            (0x41, false) => InputKeyPosition.F7,
            (0x42, false) => InputKeyPosition.F8,
            (0x43, false) => InputKeyPosition.F9,
            (0x44, false) => InputKeyPosition.F10,
            (0x45, _) when observation.VirtualKey == 0x13 => InputKeyPosition.Pause,
            (0x45, _) when observation.VirtualKey == 0x90 => InputKeyPosition.NumLock,
            (0x46, false) => InputKeyPosition.ScrollLock,
            (0x47, false) => InputKeyPosition.Numpad7,
            (0x47, true) => InputKeyPosition.Home,
            (0x48, false) => InputKeyPosition.Numpad8,
            (0x48, true) => InputKeyPosition.ArrowUp,
            (0x49, false) => InputKeyPosition.Numpad9,
            (0x49, true) => InputKeyPosition.PageUp,
            (0x4A, false) => InputKeyPosition.NumpadSubtract,
            (0x4B, false) => InputKeyPosition.Numpad4,
            (0x4B, true) => InputKeyPosition.ArrowLeft,
            (0x4C, false) => InputKeyPosition.Numpad5,
            (0x4D, false) => InputKeyPosition.Numpad6,
            (0x4D, true) => InputKeyPosition.ArrowRight,
            (0x4E, false) => InputKeyPosition.NumpadAdd,
            (0x4F, false) => InputKeyPosition.Numpad1,
            (0x4F, true) => InputKeyPosition.End,
            (0x50, false) => InputKeyPosition.Numpad2,
            (0x50, true) => InputKeyPosition.ArrowDown,
            (0x51, false) => InputKeyPosition.Numpad3,
            (0x51, true) => InputKeyPosition.PageDown,
            (0x52, false) => InputKeyPosition.Numpad0,
            (0x52, true) => InputKeyPosition.Insert,
            (0x53, false) => InputKeyPosition.NumpadDecimal,
            (0x53, true) => InputKeyPosition.Delete,
            (0x56, false) => InputKeyPosition.IntlBackslash,
            (0x57, false) => InputKeyPosition.F11,
            (0x58, false) => InputKeyPosition.F12,
            (0x5B, true) => InputKeyPosition.MetaLeft,
            (0x5C, true) => InputKeyPosition.MetaRight,
            (0x5D, true) => InputKeyPosition.ContextMenu,
            _ => default,
        };

        return position != default;
    }
}
