using Heartbeat.Dev;

namespace Heartbeat.Dev.Tests;

public sealed class WebVerificationWorkspaceTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), $"heartbeat-web-workspaces-{Guid.NewGuid():N}");

    [Fact]
    public async Task IsolatesWritableStateAndPrunesWithoutDeletingSharedDependencies()
    {
        var repository = new RepositoryContext(_root);
        var web = repository.Path("src", "Frontend", "Heartbeat.Web");
        Directory.CreateDirectory(Path.Combine(web, "node_modules"));
        File.WriteAllText(Path.Combine(web, "node_modules", "sentinel"), "dependency");
        File.WriteAllText(Path.Combine(web, "tsconfig.json"), "{}");
        File.WriteAllText(Path.Combine(web, ".env.local"), "private fixture");
        var store = new ArtifactStore(repository);
        var firstRun = store.Create("scenario", "first");
        var first = await WebVerificationWorkspace.PrepareAsync(repository, firstRun, CancellationToken.None);
        var second = await WebVerificationWorkspace.PrepareAsync(repository, store.Create("scenario", "second"), CancellationToken.None);

        File.WriteAllText(Path.Combine(first, "tsconfig.json"), "generated by Next");
        Assert.Equal("{}", File.ReadAllText(Path.Combine(web, "tsconfig.json")));
        Assert.Equal("{}", File.ReadAllText(Path.Combine(second, "tsconfig.json")));
        Assert.False(File.Exists(Path.Combine(first, ".env.local")));
        store.Delete(firstRun);
        Assert.Equal("dependency", File.ReadAllText(Path.Combine(second, "node_modules", "sentinel")));
        Assert.Equal("dependency", File.ReadAllText(Path.Combine(web, "node_modules", "sentinel")));
    }

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, true);
    }
}
