// <auto-generated />
using System;
using Heartbeat.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Heartbeat.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829100458_AskingWindowIdentity")]
    partial class AskingWindowIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Heartbeat.Server.Entities.ActivitySegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("AppId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AppIdentityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("AppIdentityId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("StartTime");

                    b.HasIndex("DeviceId", "Source", "IdentityKey", "EndTime");

                    b.ToTable("ActivitySegments");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.App", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.AppCatalogAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("CatalogVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AppCatalogAudits");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.AppCatalogOverride", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppIdentityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBySubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("PromotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("TargetAppId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetAppKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBySubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppIdentityId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'active'");

                    b.HasIndex("TargetAppId");

                    b.ToTable("AppCatalogOverrides", t =>
                        {
                            t.HasCheckConstraint("CK_AppCatalogOverrides_ActiveTarget", "\"Status\" <> 'active' OR \"TargetAppId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.AppCatalogState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CatalogVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("StartupMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("AppCatalogStates", t =>
                        {
                            t.HasCheckConstraint("CK_AppCatalogStates_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.AppIcon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("IconData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("OwnerId", "AppId")
                        .IsUnique();

                    b.ToTable("AppIcons");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.AppIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppIdentities");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.AppMergeReceipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceAppKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("TargetAppId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetAppKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("SourceAppKey", "TargetAppKey")
                        .IsUnique();

                    b.ToTable("AppMergeReceipts");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.CollectorDeclaration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Version")
                        .IsUnique();

                    b.ToTable("CollectorDeclarations");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.DailyQuestionSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SegmentWatermark")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("WindowEndExclusive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WindowKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WindowKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WindowVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "WindowKey")
                        .IsUnique();

                    b.ToTable("DailyQuestionSets");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CurrentApp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("CurrentAppIdentityId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAppIdentityId");

                    b.HasIndex("OwnerId", "HardwareId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApproximateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ApproximateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedStrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RelatedStrandId");

                    b.HasIndex("OwnerId", "LocalDate");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.InputEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<short>("Code")
                        .HasColumnType("smallint");

                    b.Property<string>("CodeSet")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp");

                    b.ToTable("InputEvents");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.MutedMatcher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Source", "StepsJson")
                        .IsUnique();

                    b.ToTable("MutedMatchers");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.Recap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KnowledgeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LocalDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("SegmentWatermark")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("WindowEndExclusive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WindowKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WindowKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WindowVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "WindowKey")
                        .IsUnique();

                    b.ToTable("Recaps");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.RecurrenceProbe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Status");

                    b.HasIndex("EpisodeId", "Source", "StepsJson")
                        .IsUnique();

                    b.ToTable("RecurrenceProbes");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.Strand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date");

                    b.Property<string>("Gloss")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentStrandId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartedOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentStrandId");

                    b.HasIndex("OwnerId", "ParentStrandId", "NormalizedName");

                    b.ToTable("Strands");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.StrandMatcher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StrandId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StrandId", "Source", "StepsJson")
                        .IsUnique();

                    b.ToTable("StrandMatchers");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.ActivitySegment", b =>
                {
                    b.HasOne("Heartbeat.Server.Entities.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId");

                    b.HasOne("Heartbeat.Server.Entities.AppIdentity", "AppIdentity")
                        .WithMany()
                        .HasForeignKey("AppIdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Heartbeat.Server.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("AppIdentity");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.AppCatalogOverride", b =>
                {
                    b.HasOne("Heartbeat.Server.Entities.AppIdentity", "AppIdentity")
                        .WithMany()
                        .HasForeignKey("AppIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Heartbeat.Server.Entities.App", "TargetApp")
                        .WithMany()
                        .HasForeignKey("TargetAppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppIdentity");

                    b.Navigation("TargetApp");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.AppIcon", b =>
                {
                    b.HasOne("Heartbeat.Server.Entities.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.AppIdentity", b =>
                {
                    b.HasOne("Heartbeat.Server.Entities.App", "App")
                        .WithMany("Identities")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.Device", b =>
                {
                    b.HasOne("Heartbeat.Server.Entities.AppIdentity", "CurrentAppIdentity")
                        .WithMany()
                        .HasForeignKey("CurrentAppIdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentAppIdentity");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.Episode", b =>
                {
                    b.HasOne("Heartbeat.Server.Entities.Strand", "RelatedStrand")
                        .WithMany()
                        .HasForeignKey("RelatedStrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedStrand");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.InputEvent", b =>
                {
                    b.HasOne("Heartbeat.Server.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.RecurrenceProbe", b =>
                {
                    b.HasOne("Heartbeat.Server.Entities.Episode", "Episode")
                        .WithMany("Probes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.Strand", b =>
                {
                    b.HasOne("Heartbeat.Server.Entities.Strand", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentStrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.StrandMatcher", b =>
                {
                    b.HasOne("Heartbeat.Server.Entities.Strand", "Strand")
                        .WithMany("Members")
                        .HasForeignKey("StrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strand");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.App", b =>
                {
                    b.Navigation("Identities");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.Episode", b =>
                {
                    b.Navigation("Probes");
                });

            modelBuilder.Entity("Heartbeat.Server.Entities.Strand", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
