<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Heartbeat</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Contracts/Heartbeat.Contracts/Heartbeat.Contracts.csproj" />
  </ItemGroup>
</Project>
