allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@fumadocs/base-ui@16.17.1'
  - fumadocs-core@16.17.1
  - fumadocs-test-reports@0.1.1
  - '@fumadocs/tailwind@0.1.3'
  - fumadocs-mdx@15.4.7
  - fumadocs-openapi@12.4.1
