<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Hub/Heartbeat.Hub.Client/Heartbeat.Hub.Client.csproj" />
    <ProjectReference Include="../../src/Hub/Heartbeat.Hub/Heartbeat.Hub.csproj" />
    <ProjectReference Include="../../src/Backend/Heartbeat.Api/Heartbeat.Api.csproj" />
    <ProjectReference Include="../../src/Backend/Heartbeat.Application/Heartbeat.Application.csproj" />
    <ProjectReference Include="../../src/Backend/Heartbeat.Domain/Heartbeat.Domain.csproj" />
    <ProjectReference Include="../../src/Backend/Heartbeat.Infrastructure/Heartbeat.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
