// <auto-generated />
using System;
using System.Text.Json;
using Heartbeat.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Heartbeat.Persistence.Migrations
{
    [DbContext(typeof(HeartbeatDbContext))]
    [Migration("20260912064231_InitialRecordingModel")]
    partial class InitialRecordingModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Heartbeat.Management.HubNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("StatusJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("hubs", (string)null);
                });

            modelBuilder.Entity("Heartbeat.Recording.ObservedObject", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid>("TimelineId").HasColumnType("uuid").HasColumnName("timeline_id");
                    b.Property<string>("Namespace").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("identity_namespace");
                    b.Property<string>("Key").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("identity_key");
                    b.Property<string>("Name").HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("name");
                    b.Property<DateTimeOffset?>("NameObservedAt").HasColumnType("timestamp with time zone").HasColumnName("name_observed_at");
                    b.Property<Guid?>("NameRecordId").HasColumnType("uuid").HasColumnName("name_record_id");
                    b.HasKey("Id");
                    b.HasIndex("TimelineId", "Namespace", "Key").IsUnique();
                    b.ToTable("objects");
                });
            modelBuilder.Entity("Heartbeat.Recording.RecordObject", b =>
                {
                    b.Property<Guid>("RecordId").HasColumnType("uuid").HasColumnName("record_id");
                    b.Property<Guid>("ObjectId").HasColumnType("uuid").HasColumnName("object_id");
                    b.Property<string>("Role").HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("role");
                    b.HasKey("RecordId", "ObjectId", "Role");
                    b.HasIndex("ObjectId", "RecordId");
                    b.ToTable("record_objects");
                });
            modelBuilder.Entity("Heartbeat.Recording.Collector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target");

                    b.Property<Guid>("TimelineId")
                        .HasColumnType("uuid")
                        .HasColumnName("timeline_id");

                    b.HasKey("Id");

                    b.HasIndex("TimelineId", "Key", "Target")
                        .IsUnique();

                    b.ToTable("collectors", null, t =>
                        {
                            t.HasCheckConstraint("ck_collectors_display_name", "btrim(display_name) <> ''");

                            t.HasCheckConstraint("ck_collectors_key", "btrim(key) <> ''");

                            t.HasCheckConstraint("ck_collectors_target", "btrim(target) <> ''");
                        });
                });

            modelBuilder.Entity("Heartbeat.Recording.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset?>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<string>("Objects").IsRequired().HasColumnType("jsonb").HasColumnName("objects");

                    b.Property<JsonElement>("Value")
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TrackId", "StartedAt", "Id")
                        .HasDatabaseName("ix_records_track_time");

                    b.ToTable("records", null, t =>
                        {
                            t.HasCheckConstraint("ck_records_time_range", "ended_at IS NULL OR ended_at >= started_at");
                        });
                });

            modelBuilder.Entity("Heartbeat.Recording.Timeline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("timelines", null, t =>
                        {
                            t.HasCheckConstraint("ck_timelines_display_name", "btrim(display_name) <> ''");
                        });
                });

            modelBuilder.Entity("Heartbeat.Recording.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TimeMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_mode");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CollectorId", "Type", "Version")
                        .IsUnique();

                    b.ToTable("tracks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tracks_time_mode", "time_mode IN ('point', 'range')");

                            t.HasCheckConstraint("ck_tracks_type", "btrim(type) <> ''");

                            t.HasCheckConstraint("ck_tracks_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Heartbeat.Recording.Collector", b =>
                {
                    b.HasOne("Heartbeat.Recording.Timeline", null)
                        .WithMany()
                        .HasForeignKey("TimelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Heartbeat.Recording.Record", b =>
                {
                    b.HasOne("Heartbeat.Recording.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Heartbeat.Recording.Track", b =>
                {
                    b.HasOne("Heartbeat.Recording.Collector", null)
                        .WithMany()
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
            modelBuilder.Entity("Heartbeat.Recording.ObservedObject", b =>
                {
                    b.HasOne("Heartbeat.Recording.Timeline", null).WithMany().HasForeignKey("TimelineId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });
            modelBuilder.Entity("Heartbeat.Recording.RecordObject", b =>
                {
                    b.HasOne("Heartbeat.Recording.Record", null).WithMany().HasForeignKey("RecordId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("Heartbeat.Recording.ObservedObject", "Subject").WithMany().HasForeignKey("ObjectId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Subject");
                });
#pragma warning restore 612, 618
        }
    }
}
