// <auto-generated />
using System;
using System.Text.Json;
using Heartbeat.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Heartbeat.Infrastructure.Database.Migrations
{
    [DbContext(typeof(HeartbeatDbContext))]
    partial class HeartbeatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Heartbeat.Core.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_id");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("end_at");

                    b.Property<Guid>("ObserverId")
                        .HasColumnType("uuid")
                        .HasColumnName("observer_id");

                    b.Property<Guid>("SchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("schema_id");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_at");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_observations");

                    b.ToTable("observations", null, t =>
                        {
                            t.HasCheckConstraint("ck_observations_time_order", "start_at <= end_at");
                        });
                });

            modelBuilder.Entity("Heartbeat.Core.ObservationSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<JsonElement>("Schema")
                        .HasColumnType("jsonb")
                        .HasColumnName("schema");

                    b.HasKey("Id")
                        .HasName("pk_observation_schemas");

                    b.ToTable("observation_schemas", (string)null);
                });

            modelBuilder.Entity("Heartbeat.Core.Observer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_observers");

                    b.ToTable("observers", (string)null);
                });

            modelBuilder.Entity("Heartbeat.Infrastructure.Database.EntityDataRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonElement>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.HasKey("Id")
                        .HasName("pk_entity_data");

                    b.ToTable("entity_data", (string)null);
                });

            modelBuilder.Entity("Heartbeat.Infrastructure.Database.EntityIndexRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.HasKey("Id")
                        .HasName("pk_entities");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("Heartbeat.Core.Observation", b =>
                {
                    b.HasOne("Heartbeat.Infrastructure.Database.EntityIndexRow", null)
                        .WithOne()
                        .HasForeignKey("Heartbeat.Core.Observation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observations_entities_id");
                });

            modelBuilder.Entity("Heartbeat.Core.ObservationSchema", b =>
                {
                    b.HasOne("Heartbeat.Infrastructure.Database.EntityIndexRow", null)
                        .WithOne()
                        .HasForeignKey("Heartbeat.Core.ObservationSchema", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observation_schemas_entities_id");
                });

            modelBuilder.Entity("Heartbeat.Core.Observer", b =>
                {
                    b.HasOne("Heartbeat.Infrastructure.Database.EntityIndexRow", null)
                        .WithOne()
                        .HasForeignKey("Heartbeat.Core.Observer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observers_entities_id");
                });

            modelBuilder.Entity("Heartbeat.Infrastructure.Database.EntityDataRow", b =>
                {
                    b.HasOne("Heartbeat.Infrastructure.Database.EntityIndexRow", null)
                        .WithOne()
                        .HasForeignKey("Heartbeat.Infrastructure.Database.EntityDataRow", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entity_data_entities_id");
                });
#pragma warning restore 612, 618
        }
    }
}
